version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  node-tests:
    jobs:
      working_directory: ~/PokeDex
      docker:
        - image: circleci/node:10-browsers
      steps:
        # Checkout the code from the branch into the working_directory
        - checkout
        # Log the current branch
        - run: echo ${CIRCLE_BRANCH}
        - run: npm install
        # Lint the source code
        - run: npm run lint
        # Test the source code
        - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
        # End to End test
        - run: npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js